import { Student, Course, Announcement, CourseMaterial, AttendanceSession, AttendanceRecord } from './types';

export const INITIAL_STUDENTS: Student[] = [
  { nim: '2530311065', name: 'Moh. Raihan', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311086', name: 'Sufyan Tsaury', gender: 'L', isPinSet: true, pin: '123456', status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311003', name: 'Wahdan Hamdun', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311063', name: 'Rizqi Asdi Pauzi', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311085', name: 'Syahrul Abdul Latif', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311036', name: 'Annissa Nurdieni Utami', gender: 'P', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311043', name: 'Suci Angellina', gender: 'P', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311004', name: 'Mishbah Fauzi S R', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311084', name: 'Hujroh Nurullah', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311087', name: 'Fatifatul Alzahra', gender: 'P', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311009', name: 'Mohamad Rizky Mubarok', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311089', name: 'Nurlela Hasanah', gender: 'P', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311088', name: 'Mohamad Choirun Nabik Endirob', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311010', name: 'Gilang Ahmad Rizqi', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311028', name: 'Titi Zumayka', gender: 'P', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311083', name: 'Topan Fadilah', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311061', name: 'Ahmad Hanif Mun\'im', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311060', name: 'Alfin Aufa', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311062', name: 'Alfan Ibnu Sulaeman', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311068', name: 'Mochamad Firmansyah Andika Putra', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311005', name: 'Agung Faujan Ramdani', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311067', name: 'Faiz Nur Fajar', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311069', name: 'Rafa Erlansyah Putra', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311080', name: 'Fahra Siti Al Khumaira', gender: 'P', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311031', name: 'Firda Amalinda Hutami', gender: 'P', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311081', name: 'Subhan Nur Rochman', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311012', name: 'Pramady Ahmad Faqih', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311026', name: 'Tasya Larasaty', gender: 'P', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311045', name: 'Dhurrotul Khikmah', gender: 'P', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311049', name: 'Muhammad Hasbiyallah', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'hadits-hukum-keluarga',
    code: 'HKI-301',
    name: 'Hadits Hukum Keluarga',
    dosen: 'Dr. H. Ahmad Dahlan, M.Ag.',
    sks: 2,
    semester: 3,
    day: 'Senin',
    time: '07:30 - 09:10 WIB',
    room: 'Ruang 204 Gedung FASYA',
    pjNims: ['2530311065', '2530311003'], // Moh. Raihan, Wahdan Hamdun
    description: 'Kajian hadits-hadits ahkam seputar munakahat, nafkah, hak-kewajiban suami istri, hadhanah, dan thalaq dalam tinjauan sanad dan matan.',
    driveLink: 'https://drive.google.com/drive/folders/hadits-hk-2025',
    rpsLink: '#',
  },
  {
    id: 'hukum-agraria',
    code: 'HKI-302',
    name: 'Hukum Agraria',
    dosen: 'Dr. Hj. Nurul Fadhilah, S.H., M.H.',
    sks: 2,
    semester: 3,
    day: 'Senin',
    time: '09:30 - 11:10 WIB',
    room: 'Ruang 204 Gedung FASYA',
    pjNims: ['2530311063', '2530311085'], // Rizqi Asdi Pauzi, Syahrul Abdul Latif
    description: 'Konsep hukum pertanahan nasional, UUPA No. 5 Tahun 1960, hak-hak atas tanah, pendaftaran tanah, dan sengketa agraria dalam konteks syariah.',
    driveLink: 'https://drive.google.com/drive/folders/hukum-agraria-2025',
  },
  {
    id: 'hukum-bisnis-islam',
    code: 'HKI-303',
    name: 'Hukum Bisnis Islam',
    dosen: 'H. M. Syukron, M.E.Sy.',
    sks: 2,
    semester: 3,
    day: 'Selasa',
    time: '08:00 - 09:40 WIB',
    room: 'Ruang 205 Gedung FASYA',
    pjNims: ['2530311036', '2530311043'], // Annissa Nurdieni Utami, Suci Angellina
    description: 'Akad-akad muamalah kontemporer, perbankan syariah, fintech syariah, perlindungan konsumen syariah, dan sengketa bisnis ekonomi Islam.',
    driveLink: 'https://drive.google.com/drive/folders/hukum-bisnis-islam-2025',
  },
  {
    id: 'hukum-kewarisan-islam',
    code: 'HKI-304',
    name: 'Hukum Kewarisan Islam',
    dosen: 'Dr. H. Didin Nurul Rosidin, M.A.',
    sks: 3,
    semester: 3,
    day: 'Selasa',
    time: '10:00 - 12:30 WIB',
    room: 'Ruang 205 Gedung FASYA',
    pjNims: ['2530311086', '2530311004'], // Sufyan Tsaury, Mishbah Fauzi S R
    description: 'Asas-asas faraidh, rukun dan syarat waris, hijab-mahjub, mawani\' al-irts, metode penghitungan bagian ahli waris, serta implementasi KHI di Indonesia.',
    driveLink: 'https://drive.google.com/drive/folders/hukum-kewarisan-islam-2025',
  },
  {
    id: 'hukum-perdata-internasional',
    code: 'HKI-305',
    name: 'Hukum Perdata Internasional',
    dosen: 'Prof. Dr. H. Jamali, M.Ag.',
    sks: 2,
    semester: 3,
    day: 'Rabu',
    time: '08:00 - 09:40 WIB',
    room: 'Ruang 206 Gedung FASYA',
    pjNims: ['2530311087', '2530311009'], // Fatifatul Alzahra, Mohamad Rizky Mubarok
    description: 'Prinsip-prinsip HPI, titik taut primer dan sekunder, kualifikasi hukum, perkawinan campuran antar-warga negara, dan adopsi internasional.',
    driveLink: 'https://drive.google.com/drive/folders/hpi-2025',
  },
  {
    id: 'hukum-perdata-islam-indonesia',
    code: 'HKI-306',
    name: 'Hukum Perdata Islam di Indonesia',
    dosen: 'Dr. H. Ayep Rosidi, M.Ag.',
    sks: 3,
    semester: 3,
    day: 'Rabu',
    time: '10:00 - 12:30 WIB',
    room: 'Ruang 206 Gedung FASYA',
    pjNims: ['2530311088', '2530311010'], // Mohamad Choirun Nabik Endirob, Gilang Ahmad Rizqi
    description: 'Positivisasi hukum Islam di Indonesia, Kompilasi Hukum Islam (Inpres No. 1/1991), Undang-Undang Peradilan Agama, wakaf, dan hibah.',
    driveLink: 'https://drive.google.com/drive/folders/hp-islam-indonesia-2025',
  },
  {
    id: 'hukum-perkawinan-islam',
    code: 'HKI-307',
    name: 'Hukum Perkawinan Islam',
    dosen: 'Dr. Hj. Masri\'ah, M.Ag.',
    sks: 3,
    semester: 3,
    day: 'Kamis',
    time: '08:00 - 10:30 WIB',
    room: 'Ruang 204 Gedung FASYA',
    pjNims: ['2530311028', '2530311083'], // Titi Zumayka, Topan Fadilah
    description: 'Kajian UU Perkawinan No. 1/1974 jo UU 16/2019, fikih munakahat empat mazhab, perceraian, batas usia nikah, poligami, dan pembaharuan hukum keluarga Islam.',
    driveLink: 'https://drive.google.com/drive/folders/hukum-perkawinan-islam-2025',
  },
  {
    id: 'ilmu-tafsir',
    code: 'HKI-308',
    name: 'Ilmu Tafsir',
    dosen: 'Dr. H. Aan Jaelani, M.Ag.',
    sks: 2,
    semester: 3,
    day: 'Kamis',
    time: '10:45 - 12:25 WIB',
    room: 'Ruang 204 Gedung FASYA',
    pjNims: ['2530311061', '2530311060'], // Ahmad Hanif Mun'im, Alfin Aufa
    description: 'Kaidah-kaidah penafsiran Al-Qur\'an, manhaj tafsir bil ma\'tsur dan bil ra\'yi, asbabun nuzul ayat ahkam keluarga, dan hermeneutika kontemporer.',
    driveLink: 'https://drive.google.com/drive/folders/ilmu-tafsir-2025',
  },
  {
    id: 'praktik-ibadah-1',
    code: 'HKI-309',
    name: 'Praktik Ibadah 1',
    dosen: 'Drs. H. Anwar Sanusi, M.Ag.',
    sks: 2,
    semester: 3,
    day: 'Jumat',
    time: '07:30 - 09:10 WIB',
    room: 'Masjid Kampus Al-Jami\'ah UIN SSC',
    pjNims: ['2530311062', '2530311068'], // Alfan Ibnu Sulaeman, Mochamad Firmansyah Andika Putra
    description: 'Praktik thaharah, fardhu shalat jenazah, manasik haji dan umrah, tata cara khutbah jum\'at, dan adab muamalah keagamaan praktis.',
    driveLink: 'https://drive.google.com/drive/folders/praktik-ibadah-2025',
  },
  {
    id: 'qowaid-fiqhiyah',
    code: 'HKI-310',
    name: 'Qowaid Fiqhiyah',
    dosen: 'Dr. H. Ilman Nafi\'a, M.Ag.',
    sks: 2,
    semester: 3,
    day: 'Jumat',
    time: '09:30 - 11:10 WIB',
    room: 'Ruang 205 Gedung FASYA',
    pjNims: ['2530311005', '2530311067'], // Agung Faujan Ramdani, Faiz Nur Fajar
    description: 'Lima kaidah asasiyah (al-qawa\'id al-khams), kaidah-kaidah cabang muamalah dan ahwal syakhshiyyah, serta penerapannya dalam fatwa kontemporer.',
    driveLink: 'https://drive.google.com/drive/folders/qowaid-fiqhiyah-2025',
  },
  {
    id: 'tarikh-tasyrii',
    code: 'HKI-311',
    name: 'Tarikh Tasyri’i',
    dosen: 'Dr. H. Farihin, M.Pd.',
    sks: 2,
    semester: 3,
    day: 'Sabtu',
    time: '08:30 - 10:10 WIB',
    room: 'Cyber Smart Classroom 3 / Online CIU',
    pjNims: ['2530311069', '2530311080'], // Rafa Erlansyah Putra, Fahra Siti Al Khumaira
    description: 'Sejarah pembentukan dan perkembangan hukum Islam mulai dari periode Rasulullah, Khulafaur Rasyidin, tabi\'in, era kodifikasi mazhab, hingga era modern.',
    driveLink: 'https://drive.google.com/drive/folders/tarikh-tasyrii-2025',
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Pemberitahuan Perkuliahan Semester Ganjil 2025/2026',
    content: 'Seluruh mahasiswa HK A 2025 dimohon memeriksa jadwal perkuliahan 11 mata kuliah. Jangan lupa mengisi presensi pada setiap sesi perkuliahan melalui portal ini.',
    category: 'PENTING',
    author: 'Admin Kelas HK A',
    date: '2025-09-01',
    pinned: true,
  },
  {
    id: 'ann-2',
    title: 'Pembagian Tugas Makalah & Presentasi Kelompok HKI',
    content: 'Tugas kelompok pemateri mata kuliah Hukum Kewarisan Islam telah ditentukan (14 kelompok). Silakan cek materi masing-masing kelompok pada menu repositori mata kuliah.',
    category: 'TUGAS',
    author: 'PJ Hukum Kewarisan Islam',
    date: '2025-09-01',
    pinned: true,
  },
  {
    id: 'ann-3',
    title: 'Aktivasi PIN Mahasiswa Baru',
    content: 'Bagi rekan-rekan yang baru pertama kali masuk ke website kelas, masukkan NIM Anda lalu buat 6-digit PIN keamanan pribadi untuk melindungi akun Anda.',
    category: 'AKADEMIK',
    author: 'Pengurus Kelas HK A',
    date: '2025-09-01',
  },
];

export const INITIAL_MATERIALS: CourseMaterial[] = [
  {
    id: 'mat-1',
    courseId: 'hukum-kewarisan-islam',
    title: 'RPS Lengkap & Silabus Hukum Kewarisan Islam (Semester 3)',
    type: 'RPS',
    url: 'https://drive.google.com/file/d/rps-hki-2025',
    description: 'Rencana Pembelajaran Semester lengkap dengan rincian minggu ke-1 s.d. 16.',
    uploadedBy: 'PJ Hukum Kewarisan Islam',
    uploadedAt: '2025-09-01',
    fileSize: '1.4 MB',
  },
  {
    id: 'mat-2',
    courseId: 'hukum-kewarisan-islam',
    title: 'Pembagian 14 Kelompok Pemateri HKI HK A 2025',
    type: 'MODUL',
    url: 'https://drive.google.com/file/d/kelompok-hki-2025',
    description: 'Daftar nama anggota kelompok, NIM, dan judul materi presentasi semester.',
    uploadedBy: 'PJ Hukum Kewarisan Islam',
    uploadedAt: '2025-09-01',
    fileSize: '36.8 KB',
  },
  {
    id: 'mat-3',
    courseId: 'hadits-hukum-keluarga',
    title: 'Kitab Bulughul Maram — Bab Munakahat & Syarah Ringkas',
    type: 'MODUL',
    url: 'https://drive.google.com/file/d/hadits-munakahat',
    description: 'Teks arab dan terjemahan hadits-hadits perkawinan untuk pegangan perkuliahan.',
    uploadedBy: 'PJ Hadits Hukum Keluarga',
    uploadedAt: '2025-09-01',
    fileSize: '2.8 MB',
  },
  {
    id: 'mat-4',
    courseId: 'qowaid-fiqhiyah',
    title: 'Ringkasan 5 Kaidah Asasiyah Fiqhiyah',
    type: 'MODUL',
    url: 'https://drive.google.com/file/d/kaidah-asasiyah',
    description: 'Modul pengantar kaidah fiqih asasi beserta dalil Al-Qur\'an dan Hadits.',
    uploadedBy: 'PJ Qowaid Fiqhiyah',
    uploadedAt: '2025-09-01',
    fileSize: '890 KB',
  },
];

// Initial Attendance Sessions
export const INITIAL_SESSIONS: AttendanceSession[] = [
  {
    id: 'sess-hki-1',
    courseId: 'hukum-kewarisan-islam',
    meetingNumber: 1,
    date: '2025-09-02',
    startTime: '10:00',
    endTime: '12:30',
    topic: 'Kontrak Belajar, Pengantar Faraidh, dan Urgensi Hukum Kewarisan Islam',
    dosenPresent: true,
    isOpenForSelfCheckin: true,
    checkinCode: '2501',
    createdAt: '2025-09-02T10:00:00Z',
    createdByNim: '2530311086',
  },
  {
    id: 'sess-hadits-1',
    courseId: 'hadits-hukum-keluarga',
    meetingNumber: 1,
    date: '2025-09-01',
    startTime: '07:30',
    endTime: '09:10',
    topic: 'Pengantar Hadits Ahkam Keluarga: Metode Takhrij & Kedudukan Sunnah',
    dosenPresent: true,
    isOpenForSelfCheckin: false,
    createdAt: '2025-09-01T07:30:00Z',
    createdByNim: '2530311065',
  },
];

// Initial Attendance Records for Session 1 HKI
export const INITIAL_RECORDS: AttendanceRecord[] = [
  { id: 'rec-1', sessionId: 'sess-hki-1', courseId: 'hukum-kewarisan-islam', studentNim: '2530311086', status: 'HADIR', timestamp: '2025-09-02T10:05:00Z', verifiedBy: 'MANDIRI' },
  { id: 'rec-2', sessionId: 'sess-hki-1', courseId: 'hukum-kewarisan-islam', studentNim: '2530311065', status: 'HADIR', timestamp: '2025-09-02T10:08:00Z', verifiedBy: 'MANDIRI' },
  { id: 'rec-3', sessionId: 'sess-hki-1', courseId: 'hukum-kewarisan-islam', studentNim: '2530311003', status: 'HADIR', timestamp: '2025-09-02T10:11:00Z', verifiedBy: 'PJ' },
  { id: 'rec-4', sessionId: 'sess-hki-1', courseId: 'hukum-kewarisan-islam', studentNim: '2530311063', status: 'HADIR', timestamp: '2025-09-02T10:15:00Z', verifiedBy: 'PJ' },
  { id: 'rec-5', sessionId: 'sess-hki-1', courseId: 'hukum-kewarisan-islam', studentNim: '2530311036', status: 'IZIN', notes: 'Ada kegiatan ormawa kampus', timestamp: '2025-09-02T10:16:00Z', verifiedBy: 'PJ' },
];
