import { Student, Course, Announcement, CourseMaterial, AttendanceSession, AttendanceRecord } from './types';

export const INITIAL_STUDENTS: Student[] = [
  { nim: '2530311003', name: 'Wahdan Hamdun', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311004', name: 'Mishbah Fauzi S R', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311005', name: 'Agung Faujan Ramdani', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311009', name: 'Mohamad Rizky Mubarok', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311010', name: 'Gilang Ahmad Rizqi', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311012', name: 'Pramady Ahmad Faqih', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311026', name: 'Tasya Larasaty', gender: 'P', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311028', name: 'Titi Zumayka', gender: 'P', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311031', name: 'Firda Amalinda Hutami', gender: 'P', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311036', name: 'Annissa Nurdieni Utami', gender: 'P', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311043', name: 'Suci Angellina', gender: 'P', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311045', name: 'Dhurrotul Khikmah', gender: 'P', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311049', name: 'Muhammad Hasbiyallah', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311060', name: 'Alfin Aufa', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311061', name: 'Ahmad Hanif Mun\'im', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311062', name: 'Alfan Ibnu Sulaeman', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311063', name: 'Rizqi Asdi Pauzi', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311065', name: 'Moh. Raihan', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311067', name: 'Faiz Nur Fajar', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311068', name: 'Mochamad Firmansyah Andika Putra', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311069', name: 'Rafa Erlansyah Putra', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311080', name: 'Fahra Siti Al Khumaira', gender: 'P', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311081', name: 'Subhan Nur Rochman', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311083', name: 'Topan Fadilah', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311084', name: 'Hujroh Nurullah', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311085', name: 'Syahrul Abdul Latif', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311086', name: 'Sufyan Tsaury', gender: 'L', isPinSet: true, pin: '123456', status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311087', name: 'Fatifatul Alzahra', gender: 'P', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311088', name: 'Mohamad Choirun Nabik Endirob', gender: 'L', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311089', name: 'Nurlela Hasanah', gender: 'P', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311093', name: 'Arum Khoerunisa', gender: 'P', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
  { nim: '2530311095', name: 'Lia Safitri', gender: 'P', isPinSet: false, status: 'AKTIF', createdAt: '2025-09-01' },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'hadits-hukum-keluarga',
    code: 'HKI-301',
    name: 'Hadits Hukum Keluarga',
    dosen: 'Prof. Dr. H. Faqiuddin Abdul Kodir, M.A.',
    sks: 3,
    semester: 3,
    day: 'Senin',
    time: '07:30 - 10:00 WIB',
    room: 'G 204',
    pjNims: ['2530311087', '2530311045'], // Fatifatul Alzahra, Dhurrotul Khikmah
    description: 'Kajian hadits-hadits ahkam seputar munakahat, nafkah, hak-kewajiban suami istri, hadhanah, dan thalaq.',
    driveLink: '',
    rpsLink: '#',
  },
  {
    id: 'hukum-perkawinan-islam',
    code: 'HKI-307',
    name: 'Hukum Perkawinan Islam',
    dosen: 'Akhmad Shodikin S.Ag. M.H.I',
    sks: 3,
    semester: 3,
    day: 'Senin',
    time: '10:00 - 12:30 WIB',
    room: 'R 03',
    pjNims: ['2530311009', '2530311062'], // Mohamad Rizky Mubarok, Alfan Ibnu Sulaeman
    description: 'UU Perkawinan No. 1/1974 jo UU 16/2019, fikih munakahat empat mazhab, dan perceraian.',
    driveLink: '',
  },
  {
    id: 'hukum-kewarisan-islam',
    code: 'HKI-304',
    name: 'Hukum Kewarisan Islam',
    dosen: 'Prof. Dr.H. Kosim. M.Ag.',
    sks: 3,
    semester: 3,
    day: 'Selasa',
    time: '07:30 - 10:00 WIB',
    room: 'G 204',
    pjNims: ['2530311036', '2530311065'], // Annissa Nurdieni Utami, Moh. Raihan
    description: "Asas faraidh, rukun waris, hijab-mahjub, mawani' al-irts, dan implementasi KHI di Indonesia.",
    driveLink: '',
  },
  {
    id: 'hukum-perdata-islam-indonesia',
    code: 'HKI-306',
    name: 'Hukum Perdata Islam di Indonesia',
    dosen: 'Dr. H. Asep Saepullah. M.H.I',
    sks: 2,
    semester: 3,
    day: 'Selasa',
    time: '10:50 - 12:30 WIB',
    room: 'R 02',
    pjNims: ['2530311031', '2530311028'], // Firda Amalinda Hutami, Titi Zumayka
    description: 'Positivisasi hukum Islam, Kompilasi Hukum Islam (Inpres No. 1/1991), dan UU Peradilan Agama.',
    driveLink: '',
  },
  {
    id: 'ilmu-tafsir',
    code: 'HKI-308',
    name: 'Ilmu Tafsir',
    dosen: 'Dr. Ahmad Alamudin Yasin M.H',
    sks: 2,
    semester: 3,
    day: 'Rabu',
    time: '09:10 - 10:50 WIB',
    room: 'Lab Lt 3 Ruang 04 Fasya',
    pjNims: ['2530311005', '2530311049'], // Agung Faujan Ramdani, Muhammad Hasbiyallah
    description: "Kaidah penafsiran Al-Qur'an, manhaj tafsir, dan asbabun nuzul ayat-ayat ahkam keluarga.",
    driveLink: '',
  },
  {
    id: 'tarikh-tasyrii',
    code: 'HKI-311',
    name: 'Tarikh Tasyri’i',
    dosen: 'Dr. Achmad Otong Bustomi. Lc. M.Ag.',
    sks: 2,
    semester: 3,
    day: 'Rabu',
    time: '10:50 - 12:30 WIB',
    room: 'G 202',
    pjNims: ['2530311065', '2530311068'], // Moh. Raihan, Mochamad Firmansyah Andika Putra
    description: 'Sejarah pembentukan dan perkembangan hukum Islam dari era Rasulullah hingga era modern.',
    driveLink: '',
  },
  {
    id: 'qowaid-fiqhiyah',
    code: 'HKI-310',
    name: 'Qowaid Fiqhiyah',
    dosen: 'Dr. H. Edy Setyawan. Lc. M.A.',
    sks: 3,
    semester: 3,
    day: 'Rabu',
    time: '13:00 - 15:30 WIB',
    room: 'Ruang R 01  FASYA',
    pjNims: ['2530311005', '2530311010'], // Agung Faujan Ramdani, Gilang Ahmad Rizqi
    description: "Lima kaidah asasiyah fiqhiyah (al-qawa'id al-khams) dan aplikasi fatwa kontemporer.",
    driveLink: '',
  },
  {
    id: 'praktik-ibadah-1',
    code: 'HKI-309',
    name: 'Praktik Ibadah 1',
    dosen: '-',
    sks: 2,
    semester: 3,
    day: 'Jumat',
    time: '07:30 - 09:10 WIB',
    room: "Ma'had Al-Jami'ah UIN SSC",
    pjNims: ['2530311084', '2530311061'], // Hujroh Nurullah, Ahmad Hanif Mun'im
    description: 'Praktik thaharah, fardhu shalat jenazah, manasik haji/umrah, dan tata cara khutbah.',
    driveLink: '',
  },
  {
    id: 'hukum-agraria',
    code: 'HKI-302',
    name: 'Hukum Agraria',
    dosen: 'H. Awaludin M.Kn',
    sks: 2,
    semester: 3,
    day: 'Jumat',
    time: '07:30 - 09:10 WIB',
    room: 'R 02',
    pjNims: ['2530311004', '2530311012'], // Mishbah Fauzi S R, Pramady Ahmad Faqih
    description: 'Konsep hukum pertanahan nasional, UUPA No. 5 Tahun 1960, pendaftaran tanah, dan hak milik.',
    driveLink: '',
  },
  {
    id: 'hukum-perdata-internasional',
    code: 'HKI-305',
    name: 'Hukum Perdata Internasional',
    dosen: 'Mochamad Fahmi Firmansyah. S.Sy. M.A.',
    sks: 2,
    semester: 3,
    day: 'Jumat',
    time: '09:10 - 10:50 WIB',
    room: 'Lab Lt 3 Ruang 01 FASYA',
    pjNims: ['2530311065', '2530311086'], // Moh. Raihan, Sufyan Tsaury
    description: 'Prinsip HPI, titik taut, kualifikasi hukum, perkawinan campuran, dan adopsi internasional.',
    driveLink: '',
  },
  {
    id: 'hukum-bisnis-islam',
    code: 'HKI-303',
    name: 'Hukum Bisnis Islam',
    dosen: 'Ahmad Khoirudin. M.H.',
    sks: 2,
    semester: 3,
    day: 'Jumat',
    time: '13:00 - 14:40 WIB',
    room: 'R 05 FASYA',
    pjNims: ['2530311063', '2530311080'], // Rizqi Asdi Pauzi, Fahra Siti Al Khumaira
    description: 'Akad-akad muamalah kontemporer, perbankan syariah, fintech syariah, dan sengketa bisnis.',
    driveLink: '',
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Pemberitahuan Perkuliahan Semester Ganjil 2025/2026',
    content: 'Seluruh mahasiswa HK A 2025 dimohon memeriksa jadwal perkuliahan 11 mata kuliah. Jangan lupa mengisi presensi pada setiap sesi perkuliahan melalui portal ini.',
    category: 'PENTING',
    author: 'Admin Kelas HK A',
    date: '2025-09-01',
    pinned: true,
  },
  {
    id: 'ann-2',
    title: 'Pembagian Tugas Makalah & Presentasi Kelompok HKI',
    content: 'Tugas kelompok pemateri mata kuliah Hukum Kewarisan Islam telah ditentukan (14 kelompok). Silakan cek materi masing-masing kelompok pada menu repositori mata kuliah.',
    category: 'TUGAS',
    author: 'PJ Hukum Kewarisan Islam',
    date: '2025-09-01',
    pinned: true,
  },
  {
    id: 'ann-3',
    title: 'Aktivasi PIN Mahasiswa Baru',
    content: 'Bagi rekan-rekan yang baru pertama kali masuk ke website kelas, masukkan NIM Anda lalu buat 6-digit PIN keamanan pribadi untuk melindungi akun Anda.',
    category: 'AKADEMIK',
    author: 'Pengurus Kelas HK A',
    date: '2025-09-01',
  },
];

export const INITIAL_MATERIALS: CourseMaterial[] = [
  {
    id: 'mat-1',
    courseId: 'hukum-kewarisan-islam',
    title: 'RPS Lengkap & Silabus Hukum Kewarisan Islam (Semester 3)',
    type: 'RPS',
    url: 'https://drive.google.com/file/d/rps-hki-2025',
    description: 'Rencana Pembelajaran Semester lengkap dengan rincian minggu ke-1 s.d. 16.',
    uploadedBy: 'PJ Hukum Kewarisan Islam',
    uploadedAt: '2025-09-01',
    fileSize: '1.4 MB',
  },
  {
    id: 'mat-2',
    courseId: 'hukum-kewarisan-islam',
    title: 'Pembagian 14 Kelompok Pemateri HKI HK A 2025',
    type: 'MODUL',
    url: 'https://drive.google.com/file/d/kelompok-hki-2025',
    description: 'Daftar nama anggota kelompok, NIM, dan judul materi presentasi semester.',
    uploadedBy: 'PJ Hukum Kewarisan Islam',
    uploadedAt: '2025-09-01',
    fileSize: '36.8 KB',
  },
  {
    id: 'mat-3',
    courseId: 'hadits-hukum-keluarga',
    title: 'Kitab Bulughul Maram — Bab Munakahat & Syarah Ringkas',
    type: 'MODUL',
    url: 'https://drive.google.com/file/d/hadits-munakahat',
    description: 'Teks arab dan terjemahan hadits-hadits perkawinan untuk pegangan perkuliahan.',
    uploadedBy: 'PJ Hadits Hukum Keluarga',
    uploadedAt: '2025-09-01',
    fileSize: '2.8 MB',
  },
  {
    id: 'mat-4',
    courseId: 'qowaid-fiqhiyah',
    title: 'Ringkasan 5 Kaidah Asasiyah Fiqhiyah',
    type: 'MODUL',
    url: 'https://drive.google.com/file/d/kaidah-asasiyah',
    description: 'Modul pengantar kaidah fiqih asasi beserta dalil Al-Qur\'an dan Hadits.',
    uploadedBy: 'PJ Qowaid Fiqhiyah',
    uploadedAt: '2025-09-01',
    fileSize: '890 KB',
  },
];

// Initial Attendance Sessions
export const INITIAL_SESSIONS: AttendanceSession[] = [
  {
    id: 'sess-hki-1',
    courseId: 'hukum-kewarisan-islam',
    meetingNumber: 1,
    date: '2025-09-02',
    startTime: '10:00',
    endTime: '12:30',
    topic: 'Kontrak Belajar, Pengantar Faraidh, dan Urgensi Hukum Kewarisan Islam',
    dosenPresent: true,
    isOpenForSelfCheckin: true,
    checkinCode: '2501',
    createdAt: '2025-09-02T10:00:00Z',
    createdByNim: '2530311086',
  },
  {
    id: 'sess-hadits-1',
    courseId: 'hadits-hukum-keluarga',
    meetingNumber: 1,
    date: '2025-09-01',
    startTime: '07:30',
    endTime: '09:10',
    topic: 'Pengantar Hadits Ahkam Keluarga: Metode Takhrij & Kedudukan Sunnah',
    dosenPresent: true,
    isOpenForSelfCheckin: false,
    createdAt: '2025-09-01T07:30:00Z',
    createdByNim: '2530311065',
  },
];

// Initial Attendance Records for Session 1 HKI
export const INITIAL_RECORDS: AttendanceRecord[] = [
  { id: 'rec-1', sessionId: 'sess-hki-1', courseId: 'hukum-kewarisan-islam', studentNim: '2530311086', status: 'HADIR', timestamp: '2025-09-02T10:05:00Z', verifiedBy: 'MANDIRI' },
  { id: 'rec-2', sessionId: 'sess-hki-1', courseId: 'hukum-kewarisan-islam', studentNim: '2530311065', status: 'HADIR', timestamp: '2025-09-02T10:08:00Z', verifiedBy: 'MANDIRI' },
  { id: 'rec-3', sessionId: 'sess-hki-1', courseId: 'hukum-kewarisan-islam', studentNim: '2530311003', status: 'HADIR', timestamp: '2025-09-02T10:11:00Z', verifiedBy: 'PJ' },
  { id: 'rec-4', sessionId: 'sess-hki-1', courseId: 'hukum-kewarisan-islam', studentNim: '2530311063', status: 'HADIR', timestamp: '2025-09-02T10:15:00Z', verifiedBy: 'PJ' },
  { id: 'rec-5', sessionId: 'sess-hki-1', courseId: 'hukum-kewarisan-islam', studentNim: '2530311036', status: 'IZIN', notes: 'Ada kegiatan ormawa kampus', timestamp: '2025-09-02T10:16:00Z', verifiedBy: 'PJ' },
];
